#!/usr/bin/env bash

# enable color support of ls and also add handy aliases
if [ -x /usr/bin/dircolors ]; then
  test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
  alias ls='ls --color=auto'
  alias lg='ll|grep'
  alias grep='grep --color=auto --exclude=*tags'
  alias gr='grep -nr'
fi

if [ -x "$(command -v exa)" ]; then
    alias ls='exa'
    alias l='exa -labF --icons'
    alias ll='exa -lbF --icons'
    alias llm='exa -lbGd --sort=modified'
    alias la='exa -lbhHigUmuSa --time-style=long-iso --git --color-scale'
    alias lx='exa -lbhHigUmuSa@ --time-style=long-iso --git --color-scale'
    alias lS='exa -1'
    alias lt='exa --tree --level=2 --icons'
else
    alias l='ls -CF'
    alias ll='ls -ahlF'
    alias la='ls -A'
    alias lt='tree'
    alias cpr='cp -r'
fi

alias t='task'
alias tt='taskwarrior-tui'
alias ti='timew'

# quick way to get out of current directory
alias ..='cd ..'
alias ...='cd ../../../'
alias ....='cd ../../../../'
alias .2='cd ../../'
alias .3='cd ../../../'
alias .4='cd ../../../../'
alias .5='cd ../../../../..'
alias .6='cd ../../../../../..'
alias .7='cd ../../../../../../..'
alias .8='cd ../../../../../../../..'
alias ~="cd ~"
alias - -="cd -"

alias path='echo -e ${PATH//:/\\n}'

if [ -x "$(command -v exa)" ]; then
    alias u='sudo nala update && sudo nala upgrade'
else
    alias u='sudo apt -y update && sudo apt -y upgrade'
fi

alias mmd="fortune | cowsay && echo ' '"

if [ -x "$(command -v fzf)" ]; then
    alias ff='vim $(fzf)'
fi

## reboot / halt / poweroff
alias reboot='sudo /sbin/reboot'
alias poweroff='sudo /sbin/poweroff'
alias shutdown='sudo /sbin/shutdown'
alias killjobs='pids=( $(jobs -p) ); [ -n "$pids" ] && kill -- "${pids[@]/#/-}"'

# Always enable colored `grep` output
alias grep='grep --color=auto'
alias fgrep='fgrep --color=auto'
alias egrep='egrep --color=auto'

# Enable aliases to be sudo’ed
alias sudo='sudo '

# Get week number
alias week='date +%V'

# Intuitive map function
# For example, to list all directories that contain a certain file:
# find . -name .gitattributes | map dirname
alias map="xargs -n1"

# Reload the shell (i.e. invoke as a login shell)
alias reload="exec ${SHELL} -l"

alias vim="nvim"
alias vi="nvim"

vman () { text=$(man "$@") && echo "$text" | vim -R +":set ft=man" - ; }
