# ==================================================================
# module list
# ------------------------------------------------------------------
# python        3.6         (apt)
# jupyterlab    latest      (pip)
# pytorch       1.0         (pip)
# tensorflow    2.0.0-alpha (pip)
# keras         latest      (pip)
# fastai        latest      (pip)
# opencv        4.0.1       (git)
# ==================================================================

FROM nvidia/cuda:10.0-cudnn7-devel-ubuntu18.04
MAINTAINER Austin Chen austin.yhc@gmail.com
ENV LANG C.UTF-8
RUN APT_INSTALL="apt-get install -y --no-install-recommends" &&     \
    PIP_INSTALL="python -m pip --no-cache-dir install --upgrade" && \
    GIT_CLONE="git clone --depth 10" &&                             \
                                                                    \
    rm -rf /var/lib/apt/lists/*                                     \
           /etc/apt/sources.list.d/cuda.list                        \
           /etc/apt/sources.list.d/nvidia-ml.list &&                \
                                                                    \
    apt-get update &&                                               \
                                                                    \
# ==================================================================
# tools
# ------------------------------------------------------------------
                                                                    \
    DEBIAN_FRONTEND=noninteractive $APT_INSTALL                     \
        build-essential                                             \
        apt-utils                                                   \
        ca-certificates                                             \
        wget                                                        \
        git                                                         \
        vim                                                         \
        &&                                                          \
                                                                    \
    $GIT_CLONE https://github.com/Kitware/CMake ~/cmake &&          \
    cd ~/cmake &&                                                   \
    ./bootstrap &&                                                  \
    make -j"$(nproc)" install &&                                    \
                                                                    \
# ==================================================================
# python
# ------------------------------------------------------------------
                                                                    \
    DEBIAN_FRONTEND=noninteractive $APT_INSTALL                     \
        software-properties-common                                  \
        &&                                                          \
                                                                    \
    add-apt-repository ppa:deadsnakes/ppa &&                        \
    apt-get update &&                                               \
    DEBIAN_FRONTEND=noninteractive $APT_INSTALL                     \
        python3.6                                                   \
        python3.6-dev                                               \
        python3-distutils-extra                                     \
        &&                                                          \
                                                                    \
    wget -O ~/get-pip.py                                            \
        https://bootstrap.pypa.io/get-pip.py &&                     \
                                                                    \
    python3.6 ~/get-pip.py &&                                       \
    ln -s /usr/bin/python3.6 /usr/local/bin/python3 &&              \
    ln -s /usr/bin/python3.6 /usr/local/bin/python &&               \
                                                                    \
    $PIP_INSTALL                                                    \
        setuptools                                                  \
        &&                                                          \
    $PIP_INSTALL                                                    \
        numpy                                                       \
        scipy                                                       \
        pandas                                                      \
        cloudpickle                                                 \
        scikit-learn                                                \
        matplotlib                                                  \
        Cython                                                      \
        &&                                                          \
                                                                    \
# ==================================================================
# boost
# ------------------------------------------------------------------
                                                                    \
    wget -O ~/boost.tar.gz                                          \
        https://dl.bintray.com/boostorg/release/1.69.0/source/boost_1_69_0.tar.gz && \
    tar -zxf ~/boost.tar.gz -C ~ &&                                 \
    cd ~/boost_* &&                                                 \
    ./bootstrap.sh --with-python=python3.6 &&                       \
    ./b2 install -j"$(nproc)" --prefix=/usr/local &&                \
                                                                    \
## ==================================================================
## jupyter
## ------------------------------------------------------------------
                                                                    \
    $PIP_INSTALL                                                    \
        jupyterlab                                                  \
        &&                                                          \
                                                                    \
## ==================================================================
## pytorch
## ------------------------------------------------------------------
                                                                    \
    $PIP_INSTALL                                                    \
        future                                                      \
        numpy                                                       \
        protobuf                                                    \
        enum34                                                      \
        pyyaml                                                      \
        typing                                                      \
    	torchvision                                                 \
        &&                                                          \
    $PIP_INSTALL                                                    \
        https://download.pytorch.org/whl/cu100/torch-1.0.1.post2-cp36-cp36m-linux_x86_64.whl \
        &&                                                          \
                                                                    \
## ==================================================================
## tensorflow
## ------------------------------------------------------------------
                                                                    \
    $PIP_INSTALL                                                    \
        tensorflowi-gpu==2.0.0-alpha0                               \
        &&                                                          \
                                                                    \
## ==================================================================
## keras
## ------------------------------------------------------------------
                                                                    \
    $PIP_INSTALL                                                    \
        h5py                                                        \
        keras                                                       \
        &&                                                          \
                                                                    \
# ==================================================================
# opencv
# ------------------------------------------------------------------
#
#    DEBIAN_FRONTEND=noninteractive $APT_INSTALL \
#        libatlas-base-dev \
#        libgflags-dev \
#        libgoogle-glog-dev \
#        libhdf5-serial-dev \
#        libleveldb-dev \
#        liblmdb-dev \
#        libprotobuf-dev \
#        libsnappy-dev \
#        protobuf-compiler \
#        && \
#
#    $GIT_CLONE --branch 4.0.1 https://github.com/opencv/opencv ~/opencv && \
#    mkdir -p ~/opencv/build && cd ~/opencv/build && \
#    cmake -D CMAKE_BUILD_TYPE=RELEASE \
#          -D CMAKE_INSTALL_PREFIX=/usr/local \
#          -D WITH_IPP=OFF \
#          -D WITH_CUDA=OFF \
#          -D WITH_OPENCL=OFF \
#          -D BUILD_TESTS=OFF \
#          -D BUILD_PERF_TESTS=OFF \
#          .. && \
#    make -j"$(nproc)" install && \
#    ln -s /usr/local/include/opencv4/opencv2 /usr/local/include/opencv2 && \
#
# ==================================================================
# customization
# ------------------------------------------------------------------
                                                                    \
    $PIP_INSTALL                                                    \
        fastai                                                      \
        &&                                                          \
                                                                    \
# ==================================================================
# config & cleanup
# ------------------------------------------------------------------
                                                                    \
    ldconfig &&                                                     \
    apt-get clean &&                                                \
    apt-get autoremove &&                                           \
    rm -rf /var/lib/apt/lists/* /tmp/* ~/*

EXPOSE 8888 6006
