require("achen.plugins-setup")
require("achen.core.options")
require("achen.core.keymaps")
require("achen.core.colorscheme")
require("achen.plugins.comment")
require("achen.plugins.nvim-tree")
require("achen.plugins.lualine")
require("achen.plugins.telescope")
require("achen.plugins.nvim-cmp")
require("achen.plugins.lsp.mason")
require("achen.plugins.lsp.lspsaga")
require("achen.plugins.lsp.lspconfig")
require("achen.plugins.lsp.null-ls")
require("achen.plugins.autopairs")
-- require("achen.plugins.treesitter")
require("achen.plugins.gitsigns")
